### ISSUE TITLE
npm restart throws errors 

### ISSUE THREAD

**Issue by fredhampton** [LeoAJ/react-iTunes-search#6]
I attempted to run npm restart and received the following errors 

module.js:340
    throw err;
          ^
Error: Cannot find module 'ecstatic'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (server.js:1:1)
    at Module._compile (module.js:456:26)
    at loader (/srv/www/movie.leola.me/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/srv/www/movie.leola.me/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

npm ERR! Linux 4.4.9-rh22-20160504224432.xenU.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.10.40
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! react-iTunes-search@1.0.5 dev: `babel-node server.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the react-iTunes-search@1.0.5 dev script 'babel-node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-iTunes-search package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-iTunes-search
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-iTunes-search
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/www/movie.leola.me/npm-debug.log

npm ERR! Linux 4.4.9-rh22-20160504224432.xenU.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "restart"
npm ERR! node v0.10.40
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! react-iTunes-search@1.0.5 start: `npm run dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-iTunes-search@1.0.5 start script 'npm run dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-iTunes-search package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-iTunes-search
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-iTunes-search
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/www/movie.leola.me/npm-debug.log
root@leola:/srv/www/movie.leola.me# npm stop
npm ERR! Linux 4.4.9-rh22-20160504224432.xenU.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "stop"
npm ERR! node v0.10.40
npm ERR! npm  v3.8.6

npm ERR! missing script: stop
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/www/movie.leola.me/npm-debug.log
root@leola:/srv/www/movie.leola.me# npm restart

> react-iTunes-search@1.0.5 start /srv/www/movie.leola.me
> npm run dev

> react-iTunes-search@1.0.5 dev /srv/www/movie.leola.me
> babel-node server.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'ecstatic'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (server.js:1:1)
    at Module._compile (module.js:456:26)
    at loader (/srv/www/movie.leola.me/node_modules/babel-register/lib/node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (/srv/www/movie.leola.me/node_modules/babel-register/lib/node.js:168:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

npm ERR! Linux 4.4.9-rh22-20160504224432.xenU.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v0.10.40
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! react-iTunes-search@1.0.5 dev: `babel-node server.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the react-iTunes-search@1.0.5 dev script 'babel-node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-iTunes-search package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel-node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-iTunes-search
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-iTunes-search
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/www/movie.leola.me/npm-debug.log

npm ERR! Linux 4.4.9-rh22-20160504224432.xenU.x86_64
npm ERR! argv "node" "/usr/local/bin/npm" "restart"
npm ERR! node v0.10.40
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! react-iTunes-search@1.0.5 start: `npm run dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-iTunes-search@1.0.5 start script 'npm run dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-iTunes-search package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-iTunes-search
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-iTunes-search
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/www/movie.leola.me/npm-debug.log
root@leola:/srv/www/movie.leola.me#

**Comment by LeoAJ** [comment]
can you try to delete entire `node_modules` folder and do `npm install` again?

**Comment by fredhampton** [comment]
I deleted the node_moduels folder and ran pm install again….still receiving errors messages 


> react-iTunes-search@1.0.5 deploy /srv/www/movie.leola.me
> npm run clean && npm run build


> react-iTunes-search@1.0.5 clean /srv/www/movie.leola.me
> rimraf dist/


> react-iTunes-search@1.0.5 build /srv/www/movie.leola.me
> webpack -p --config webpack.production.config.js --progress --colors --define process.env.NODE_ENV='"production"'
                                                                                   Hash: 396f0bfb9d565b6f60f0                
Version: webpack 1.13.0
Time: 367ms
    + 1 hidden modules

ERROR in ./js/index.js
Module build failed: SyntaxError: /srv/www/movie.leola.me/js/index.js: Unexpected token (22:2)
  20 | 
  21 | render(
> 22 |   <App />,
     |   ^
  23 |   document.querySelector('#itunes-search')
  24 | );
  25 | 
    at Parser.pp.raise (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/util.js:89:8)
    at Parser.pp.parseExprAtom (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/expression.js:517:12)
    at Parser.pp.parseExprSubscripts (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/expression.js:272:19)
    at Parser.pp.parseMaybeUnary (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/expression.js:252:19)
    at Parser.pp.parseExprOps (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/expression.js:183:19)
    at Parser.pp.parseMaybeConditional (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/expression.js:165:19)
    at Parser.pp.parseMaybeAssign (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/expression.js:128:19)
    at Parser.pp.parseExprListItem (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/expression.js:1032:16)
    at Parser.pp.parseCallExpressionArguments (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/expression.js:348:20)
    at Parser.pp.parseSubscripts (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/expression.js:311:31)
    at Parser.pp.parseExprSubscripts (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/expression.js:282:15)
    at Parser.pp.parseMaybeUnary (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/expression.js:252:19)
    at Parser.pp.parseExprOps (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/expression.js:183:19)
    at Parser.pp.parseMaybeConditional (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/expression.js:165:19)
    at Parser.pp.parseMaybeAssign (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/expression.js:128:19)
    at Parser.pp.parseExpression (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/expression.js:92:19)
    at Parser.pp.parseStatement (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/statement.js:163:19)
    at Parser.pp.parseBlockBody (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/statement.js:529:21)
    at Parser.pp.parseTopLevel (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/statement.js:36:8)
    at Parser.parse (/srv/www/movie.leola.me/node_modules/babylon/lib/parser/index.js:129:19)
    at parse (/srv/www/movie.leola.me/node_modules/babylon/lib/index.js:47:47)
    at File.parse (/srv/www/movie.leola.me/node_modules/babel-core/lib/transformation/file/index.js:540:58)
    at File.parseCode (/srv/www/movie.leola.me/node_modules/babel-core/lib/transformation/file/index.js:626:20)
    at /srv/www/movie.leola.me/node_modules/babel-core/lib/transformation/pipeline.js:52:12
    at File.wrap (/srv/www/movie.leola.me/node_modules/babel-core/lib/transformation/file/index.js:586:16)
    at Pipeline.transform (/srv/www/movie.leola.me/node_modules/babel-core/lib/transformation/pipeline.js:50:17)
    at transpile (/srv/www/movie.leola.me/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/srv/www/movie.leola.me/node_modules/babel-loader/index.js:88:12)
root@leola:/srv/www/movie.leola.me# 


 

On May 9, 2016 at 9:42:19 AM, Leo Hsieh (notifications@github.com) wrote:

can you try to delete entire node_modules folder and do npm install again?

**Comment by LeoAJ** [comment]
looks like something wrong in your code.

**Comment by fredhampton** [comment]
I have not changed that part of the code that is throwing the error. 
That is the code that came with the repo 




 

On May 9, 2016 at 1:58:31 PM, Leo Hsieh (notifications@github.com) wrote:

looks like something wrong in your code.
